# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

default_platform :ios

platform :ios do
  before_all do |lane|
    cocoapods
    carthage(platform: 'iOS', cache_builds: true)
  end

  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
#match(type: 'adhoc')
    gym(scheme: "Diplomski_rad”, export_method: 'ad-hoc')
    crashlytics(
        api_token: '002d1e80e7bf3a300de583f69a92347342fc38a9',
        build_secret: 'e3df1c13235f9dab0dc7accc866329608184f2134ce261febd9bf33b9940b592',
        groups: 'Rep')
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    gym(scheme: “Production”)
    deliver
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
